#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "D:/dev/PhD/CPSC427-Winter2024/A1/cpsc-427-dev-Chicken_Template_2023/template/"

// IMPORTANT: Do not add this file to .gitignore! If you want to push to remote, do `git add A1_template/src/*` instead of `git add .`! 
// This file is needed to compile your project and TA's may need this to run our program. If your program does not run due to wrong source directory, RESTART Visual Studio and compile again.